.TH VNSTATD 1 "JUNE 2011" "version 1.11" "User Manuals"
.SH NAME

vnStat daemon \- the alternative for cron based updating

.SH SYNOPSIS

.B vnstatd
[
.B \-Ddnpsv?
] [
.B \-\-config
.I file
] [
.B \-\-daemon
] [
.B \-\-debug
] [
.B \-\-help
] [
.B \-\-noadd
] [
.B \-\-nodaemon
] [
.B \-\-pidfile
.I file
] [
.B \-\-sync
] [
.B \-\-version
]

.SH DESCRIPTION

The purpose of
.B vnstatd
is to provide a more flexible way for updating
.BR vnstat (1)
databases than what using cron for updating can provide. The daemon makes
possible updating databases more often but at the same time requires
less disk access since data can be cached and written only later to disk
at a user configurable interval. It is also able to track how interfaces
come and go without the need of additional scripts that are required with
cron based updates.
.PP
.B vnstatd
is the command for starting the daemon. The daemon can either fork
itself to run as a background process or stay attached to the terminal.
It supports logging to a user selectable file or using syslog.
.PP
Once started, the daemon will check if there are any databases available
in the database directory that has been specified in the configuration
file. New databases will be created for all available interfaces excluding
pseudo interfaces lo, lo0 and sit0 if no databases are found during startup.

.SH OPTIONS

.TP
.BI "--config " file
Use
.I file
as config file instead of using normal config file search function.

.TP
.BI "-d, --daemon"
Fork process to background and run as a daemon.

.TP
.BI "-D, --debug"
Provide additional output for debug purposes. The process will stay
attached to the terminal for output.

.TP
.BI "--noadd"
Disable automatic creation of new databases for all available interfaces
if the daemon is started with zero database found. Pseudo interfaces
lo, lo0 and sit0 are excluded from getting added.

.TP
.BI "-n, --nodaemon"
Stay in foreground attached to the current terminal and start update
process.

.TP
.BI "-p, --pidfile " file
Write the process id to
.I file
and use it for locking so that another instance of the daemon cannot
be started if the same
.I file
is specified.

.TP
.BI "-s, --sync"
Synchronize internal counters in the database with interface
counters for all available interfaces before starting traffic monitoring.
Use this option if the traffic between the previous shutdown
and the current startup of the daemon needs to be ignored. This option
isn't required in normal use because the daemon will automatically synchronize
the internal counters after a system reboot, if enought time has passed
since the daemon was previously running or if the internal counters are
clearly out of sync.

.TP
.BI "-v, --version"
Show current version.

.TP
.BI "-?, --help"
Show a command summary.

.SH CONFIGURATION

The behaviour of the daemon is configured mainly using the configuration
keywords
.BR "UpdateInterval, PollInterval"
and
.BR SaveInterval
in the configuration file.

.PP
.BR UpdateInterval
defines in seconds how often the interface data is updated.
This is similar to the run interval for alternative cron based updating.
However, the difference is that the data doesn't get written to disk
during updates.

.PP
.BR PollInterval
defines in seconds how often the list of available interfaces is checked
for possible changes. The minimum value is 2 seconds and the maximum 60
seconds.
.BR PollInterval
also defines the resolution for other intervals.

.PP
.BR SaveInterval
defines in minutes how often cached interface data is written to disk.
A write can only occur during the updating of interface data. Therefore,
the value should be a multiple of
.BR UpdateInterval
with a maximum value of 60 minutes.

.PP
The default values of
.BR UpdateInterval
20,
.BR SaveInterval
5 and
.BR PollInterval
2 are usually suitable for most systems and provide a similar behaviour
as cron based updating does but with a better resolution for interface
changes and fast interfaces.

.PP
For embedded and/or low power systems more tuned configurations are possible.
In such cases if the interfaces are mostly static the
.BR PollInterval
can be rised to around 10-30 seconds and
.BR UpdateInterval
set to 60 seconds. Higher values up to 300 seconds are possible if the
interface speed is 10 Mbit or less.
.BR SaveInterval
can be rised for example to 15, 30 or even 60 minutes depending on how
often the data needs to be viewed.

.SH SIGNALS

The daemon is listening to signals
.BR "SIGHUP, SIGINT"
and
.BR SIGTERM.
Sending the
.BR SIGHUP
signal to the daemon will cause cached data to be written to disk,
a rescan of the database directory and a reload of settings from the
configuration file. However, the pid file will not be updated even if
it's configuration setting has been changed.

.PP
.BR SIGTERM
and
.BR SIGINT
signals will cause the daemon to write all cached data to disk and
then exit.

.SH FILES

.TP
.I /var/lib/vnstat/
Default database directory. Files are named according to the monitored
interfaces.
.TP
.I /etc/vnstat.conf
Config file that will be used unless
.I $HOME/.vnstatrc
exists. See the configuration chapter and
.BR vnstat.conf (5)
for more information.
.TP
.I /var/log/vnstat.log
Log file that will be used if logging to file is enable and no other file
is specified in the config file.
.TP
.I /var/run/vnstat.pid
File used for storing the process id if no other file is specified in the
configuration file or using the command line parameter.

.SH RESTRICTIONS

Updates needs to be executed at least as often as it is possible for the interface
to generate enough traffic to wrap the kernel interface traffic counter. Otherwise
it is possible that some traffic won't be seen. This isn't an issue for 64 bit kernels
but at least one update every hour is always required in order to provide proper input.
With 32 bit kernels the maximum time between two updates depends on how fast the
interface can transfer 4 GiB. Calculated theoretical times are:
.RS
.TS
l l.
10 Mbit:        54 minutes
100 Mbit:        5 minutes
1000 Mbit:      30 seconds
.TE
.RE

However, for 1000 Mbit interfaces updating once every minute is usually a
working solution.
.PP
Virtual and aliased interfaces cannot be monitored because the kernel doesn't
provide traffic information for that type of interfaces. Such interfaces are
usually named eth0:0, eth0:1, eth0:2 etc. where eth0 is the actual interface
being aliased.

.SH AUTHOR

Teemu Toivola <tst at iki dot fi>

.SH "SEE ALSO"

.BR vnstat (1),
.BR vnstati (1),
.BR vnstat.conf (5),
.BR signal (7)
