.PHONY: dependencies_ubuntu dependencies_ubuntu_analyzer dependencies_macos

# libgd3 removal needed due to https://github.com/actions/virtual-environments/issues/2139
dependencies_ubuntu:
	apt-get --no-upgrade remove nginx libgd3
	apt-get update
	apt-get -y --no-upgrade install libsqlite3-dev libgd-dev check

dependencies_ubuntu_analyzer: dependencies_ubuntu
	apt-get -y install clang-tools

dependencies_macos:
	brew install sqlite gd check
